# Id (memory location) kavramı  
# arrayler ile listelerin id kavramı üzerinden incelenmesi.  
# mutable & immutable kavramlarının id üzerinden açıklanması:

## Id kavramı. 

ID nedir?

id(), Python'da bir build in fonksiyondur. Bir nesnenin unique identifier’ının (tanımlayıcısının) ne olduğunu verir. Bunun nasıl çalıştığına bir göz atalım.

In [1]:
a = 1
a
# a, 1 değerini içeren bir nesnedir.

1

In [2]:
# şimdi a'nın id'sine bakalım:
id(a)


# unique identifier, bellekteki bir konuma işaret ediyor ki o bir nesnedir.

2267949066544

In [3]:
# başka bir taneye daha bakalım:
b = 2
id(b)

# id(a)'nın id(b)'den farklı olduğunu görebiliyoruz

2267949066576

In [4]:
# bunu test edersek:
a = 1
b = 2 

id(a) == id(b)

False

In [5]:
# şimdi 2'ye başka bir değişken atayalım ve id'yi kontrol edelim:

c = 2

id(c)
# dikkat ederseniz c'nin id'si b'nin id'si ile aynı!!

2267949066576

In [6]:
id(c) == id(b)

True

In [7]:
print(id(c), id(b))

2267949066576 2267949066576


In [8]:
# Şimdi bunu stringlerle deneyelim.

a = "strawberry"
b = "strawberry"
print(id(a) == id(b))  # stringler aynı olduğu için id'leri aynı.

a = "strawberry"
b = "Strawberry"  # ilk harf büyük olduğu için id'leri farklı oldu.
print(id(a) == id(b))


True
False


In [9]:
# başka bir örnek yapalım:

a = 256
b = 256
print(id(a) == id(b))

a = 260
b = 260
print(id(a) == id(b))


True
False


In [10]:
id(260)

2268035842192

In [11]:
id(260)

2268035842192

## listeler ve ID 

In [12]:
list1 = [1, 2, 3]
list2 = list1
list1 is list2

""" Yukarıdaki aynı listenin list1 ve list2 olmak üzere iki farklı adı var 
ve bunun aliased (takma ad) olduğunu söyleyebiliriz.

Değişkenler nesneleri refere ederler ve bir değişkeni diğerine atarsak,
her iki değişken de aynı nesneye atıfta bulunur. Alliasing bu demektir. """

' Yukarıdaki aynı listenin list1 ve list2 olmak üzere iki farklı adı var \nve bunun aliased (takma ad) olduğunu söyleyebiliriz.\n\nDeğişkenler nesneleri refere ederler ve bir değişkeni diğerine atarsak,\nher iki değişken de aynı nesneye atıfta bulunur. Alliasing bu demektir. '

In [13]:
list1 = [1, 2, 3]
list2 = list1[:]
print(list1)
print(list2)

"""list1'in bir kopyasını list2 değişkenine çıkarttık.
daha doğrusu list1'in slicelayarak aldığımız elemanlarını list2'ye atadık. 
ve doğal olarak her iki listenin de içeriği aynı elemanlardan oluştuğunu gördük 
"""

[1, 2, 3]
[1, 2, 3]


"list1'in bir kopyasını list2 değişkenine çıkarttık.\ndaha doğrusu list1'in slicelayarak aldığımız elemanlarını list2'ye atadık. \nve doğal olarak her iki listenin de içeriği aynı elemanlardan oluştuğunu gördük \n"

In [14]:
# Fakaat:

print(id(list1) == id(list2))

"""Gördüğünüz gibi her iki (list1 ve list2) objenin id'leri farklı.
yani artık bunlar farklı iki nesne olmuşlar."""

False


"Gördüğünüz gibi her iki (list1 ve list2) objenin id'leri farklı.\nyani artık bunlar farklı iki nesne olmuşlar."

In [15]:
# eğer list1 nesnesini list3 değişkenine atasaydık: 

list1 = [1, 2, 3]
list2 = list1

print(id(list1) == id(list2))

"""bu sefer isimleri farklı olan aynı object olduklarını görürdük.
çünkü aynı object id'sini refere ediyorlar."""

True


"bu sefer isimleri farklı olan aynı object olduklarını görürdük.\nçünkü aynı object id'sini refere ediyorlar."

In [16]:
# şimdi bir liste oluşturalım ve onu slicelayarak ondan başka bir liste elde edelim.

list3 = [1,2,3,4,5,6,7,8,9]
list3

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
# liste3'ün ilk 3 elemanından yeni bir liste oluşturduk.

list_slice = list3[:3]
list_slice

[1, 2, 3]

In [18]:
# yukarda yaptığımız işlemdeki gibi yeni liste ile eski listenin
# farklı nesneler olduğunu artık biliyoruz.

print(id(list1) == id(list3))

False


In [19]:
# yeni listenin elemanlarının değerlerini değiştirelim
# ve eski listeye etki edip etmeyeceğine bakalım:

list_slice[:3] = 0, 0, 0
list_slice

# list3'ü slicelayarak oluşturduğum yeni listemin elemanlarının hepsini 0 yaptım.

[0, 0, 0]

In [20]:
list3

"""fakat orjinal liste3'üm değişmedi. 
artık buna şaşırmadık çünkü : iki liste farklı id'lere sahip farklı nesnelerdir."""

"fakat orjinal liste3'üm değişmedi. \nartık buna şaşırmadık çünkü : iki liste farklı id'lere sahip farklı nesnelerdir."

## Numpy array'ler ve id

In [21]:
# Şimdi aynı işlemi Numpy'ın arrayleriyle yapalım:

import numpy as np

In [22]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr_slice = arr[:3]
arr_slice

# arr_slice arrayini, arr arrayinin slicelayarak aldığım ilk 3 elemanınından oluşturdum.

array([1, 2, 3])

In [24]:
arr_slice[:3] = 0
arr_slice

"""arr arrayinden slicelayarak oluşturduğum arr_slice arrayinin
elamanlarının değerini değiştirerek 0 yaptım.
az önce listelerde bu işlemi yaptığımda orjinal listemde değişiklik olmamıştı."""

'arr arrayinden slicelayarak oluşturduğum arr_slice arrayinin\nelamanlarının değerini değiştirerek 0 yaptım.\naz önce listelerde bu işlemi yaptığımda orjinal listemde değişiklik olmamıştı.'

In [25]:
arr

# fakat arraylerde orjinal arrayin de değiştiğini görüyoruz.

array([0, 0, 0, 4, 5, 6, 7, 8, 9])

In [26]:
# pekiii slicelayarak oluşturduğumuz yeni array'in id'si orjinal arrayin id'siyle aynı mı?

print(id(arr_slice))
print(id(arr))

# hayır değil.

2268026477904
2268052470544


In [27]:
# Fakaat, orjinal arr arrayinin ilk 3 elemanının id'si ile
# bu elemanlardan oluşturduğum arr_slice arrayinin elemanlarının id'si aynı.

print(id(arr_slice[:3]))
print(id(arr[:3]))

"""demek ki arrayler farklı id'lere sahip farklı objeler.
fakat içindeki elemanlar aynı id'lere sahip aynı objeler."""

2268026194128
2268026194128


"demek ki arrayler farklı id'lere sahip farklı objeler.\nfakat içindeki elemanlar aynı id'lere sahip aynı objeler."

In [53]:
id(arr[5])

2268084190928

In [56]:
a = id(arr[5])
a

2268084190960

In [58]:
a

2268084190960

In [29]:
id(arr[0])

2268058236176

In [43]:
id(arr[5]) == id(arr[0])

# aynı olduklarını görüyorum. demek ki bunlar aynı nesneler.??????????????????

True

In [47]:
np.array_equal(id(arr[0]),id(arr[5]))

True

In [42]:
# is ile kontrol edersek:

id(arr[5]) is id(arr[0])

False

In [32]:
l = [1,2,3]

m = l[:]
print(l)
print(m)

[1, 2, 3]
[1, 2, 3]


In [33]:
print(id(l[0]))
print(id(l[2]))

print(id(l[0]) == id(l[2]))

# listenin içindeki elemanların id'leri farklı. bunların her biri farklı nesneler.

2267949066544
2267949066608
False


In [34]:
print(id(l[0]))
print(id(m[0]))
print(id(l[0]) == id(m[0]))

# m listesini l listenin elemanlarından oluşturduğumda;
# bu elemanlara atanan id'lerinin değişmediğini görüyoruz



2267949066544
2267949066544
True


## mutable ve immutable kavramlarının açıklanması:

In [35]:
my_list = ['cat', 'dog', 'bunny']
print(my_list)

print('Address of my_list is: {}'.format(id(my_list)))

print("Address of the first object of my_list: {}".format(id(my_list[0])))

['cat', 'dog', 'bunny']
Address of my_list is: 2268058214464
Address of the first object of my_list: 2267957526832


In [36]:
my_list[0] = "mouse"  # list nesnemin ilk değerini değiştirdim.
print(my_list)  # listemin içeriği değişti.

print('Address of my_list is: {}'.format(id(my_list)))

# fakat listemin id'si değişmedi. hafızadaki adresi aynı dolayısıyla halen aynı nesne.

print("Address of the first object of my_list: {}".format(id(my_list[0])))

# listemin değiştirdiğim ilk elemanının id'si ise farklı. 
# list object'imin id'si değişmedi. fakat içindeki ilk object'in id'si değişti.
# Bir listeyi değiştirip value'sunu yerinde değiştirdiğimizde, liste aynı adresi tutar.
# fakat içindeki değiştirdiğimiz nesnenin artık farklı bir adresi vardır. 

['mouse', 'dog', 'bunny']
Address of my_list is: 2268058214464
Address of the first object of my_list: 2268006628720


In [37]:
# Bununla birlikte, ona tekrar bir değişken atayabilirsiniz:

phrase = 'how you like me now'
phrase


'how you like me now'

In [38]:
phrase = 'do you feel lucky'
phrase

# String nesnesini değiştirmiyor; yeni bir string nesnesi yaratıyor.

'do you feel lucky'

In [39]:
phrase = 'how you like me now'
print('Address of phrase is: {}'.format(id(phrase)))

phrase = 'do you feel lucky'
print('Address of phrase is: {}'.format(id(phrase)))

Address of phrase is: 2268058306880
Address of phrase is: 2268058402128


In [40]:
# İfadenin tek bir karakterini değiştirmeye çalışalım

phrase[0] = 'D'

TypeError: 'str' object does not support item assignment