___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">DA & DVwPY</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">The Exploratory Data Analysis (EDA) Project</p>

<img src=https://i.ibb.co/wJW61Y2/Used-cars.jpg width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">AutoScout Car Price Prediction EDA</p>



## Introduction
Welcome to "***AutoScout Exploratory Data Analysis (EDA) Project***". This is the project of completing ***Data Analysis & Data Visualization*** Courses and a successful hand-over is mandatory for getting certification for both courses. **Auto Scout** data used in this project scraped from the Website of an online car trading company in 2022, and contains many features of 13 different car makes including 594 models. In this project, you will have the opportunity to apply many commonly used algorithms for Data Cleaning and Exploratory Data Analysis by using a variety of Python libraries, such as Numpy, Pandas, Matplotlib, Seaborn, Scipy, and then you will get a clean dataset for your analysis and pretictive modelling in Machine Learning Path. So you will have the chance to use all the skills you have already learned in the Data Analysis and Visualization courses.

**``In this context, the project consists of 3 parts in general:``**
* **The first part** is related to ``'Data Cleaning'``. It deals with Incorrect Headers, Incorrect Format, Anomalies, and Dropping useless columns.
* **The second part** is related to ``'Filling Data'``, in other words 'Imputation'. It deals with Missing Values. Categorical to numeric transformation, Encoding, is done as well.
* **The third part** is related to ``'Handling Outliers of Data'`` via Visualization libraries. So, some insights will be extracted.

**``SPECIAL NOTE:``**  However, you are ``free to create your own style``. You do ``NOT`` have to stick to the steps above. Nevertheless, we, the DA & DV instructors, recommend you study each part separately to create a source notebook for your further studies. 

In order to build your Portfolio in terms of the GitHub account, you need to push your solution file up to your own repository.

Please after solving the task, commit your notebook to GitHub and submit its link to LMS page where the project is settled down.

**BE NOTED:** Please ``DO NOT FORGET`` to click the submit button.

### Some Reminders on Exploratory data analysis (EDA)

Exploratory data analysis (EDA) is an especially important activity in the routine of a data analyst or scientist. It enables an in depth understanding of the dataset, define or discard hypotheses and create predictive models on a solid basis. It uses data manipulation techniques and several statistical tools to describe and understand the relationship between variables and how these can impact business. By means of EDA, we can obtain meaningful insights that can impact analysis under the following questions (If a checklist is good enough for pilots to use every flight, it’s good enough for data scientists to use with every dataset).
1. What question are you trying to solve (or prove wrong)?
2. What kind of data do you have?
3. What’s missing from the data?
4. Where are the outliers?
5. How can you add, change or remove features to get more out of your data?

**``Exploratory data analysis (EDA)``** is often an **iterative brainstorming process** where you pose a question, review the data, and develop further questions to investigate before beginning model development work. The image below shows how the brainstorming phase is connected with that of understanding the variables and how this in turn is connected again with the brainstorming phase.<br>

<img src=https://i.ibb.co/k0MC950/EDA-Process.png width="300" height="100">

[Image Credit: Andrew D.](https://towardsdatascience.com/exploratory-data-analysis-in-python-a-step-by-step-process-d0dfa6bf94ee)



# PART- 1 `( Data Cleaning )`

In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# import warnings
# warnings.filterwarnings("ignore")
# warnings.warn("this will not show")

plt.rcParams["figure.figsize"] = (10, 6)

sns.set_style("whitegrid")
pd.set_option('display.float_format', lambda x: '%.2f' % x)

# Set it None to display all rows in the dataframe
# pd.set_option('display.max_rows', None)

# pd.options.display.max_rows = 100
# pd.options.display.max_columns = 100

In [3]:
df0 = pd.read_json('as24_cars.json')
df = df0.copy()

In [4]:
df.head()

make_model         short_description               make  \
0     Mercedes-Benz A 160                       CDi  \nMercedes-Benz\n   
1   Mercedes-Benz EQE 350                      350+  \nMercedes-Benz\n   
2  Mercedes-Benz A 45 AMG          S 4Matic+ 8G-DCT  \nMercedes-Benz\n   
3  Mercedes-Benz A 35 AMG            4Matic+ 7G-DCT  \nMercedes-Benz\n   
4  Mercedes-Benz A 45 AMG  200CDI BE Line 4M 7G-DCT  \nMercedes-Benz\n   

                model                                           location  \
0     [\n, A 160 ,\n]  P.I. EL PALMAR C/FORJA 6,  11500 PUERTO DE SAN...   
1   [\n, EQE 350 ,\n]       APARTADO DE CORREOS 1032,  26140 LOGROÑO, ES   
2  [\n, A 45 AMG ,\n]  PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8...   
3  [\n, A 35 AMG ,\n]  Carrer de Provença, 31 Local,  8029 BARCELONA, ES   
4  [\n, A 45 AMG ,\n]             CARRIL ARAGONES 4,  30007 CASILLAS, ES   

        price          Body type                      Type        Doors  \
0  € 16,950.-  [\n, Compact, \n]            [\n, Used, \n]  [\n, 5, \n]   
1  € 80,900.-  [\n, Compact, \n]  [\n, Pre-registered, \n]  [\n, 4, \n]   
2  € 69,900.-  [\n, Compact, \n]            [\n, Used, \n]  [\n, 5, \n]   
3  € 46,990.-  [\n, Compact, \n]            [\n, Used, \n]  [\n, 5, \n]   
4  € 16,800.-  [\n, Compact, \n]            [\n, Used, \n]  [\n, 5, \n]   

   Country version  ... CO₂-efficiency Fuel consumption (WLTP)  \
0  [\n, Spain, \n]  ...            NaN                     NaN   
1  [\n, Spain, \n]  ...            NaN                     NaN   
2  [\n, Spain, \n]  ...            NaN                     NaN   
3  [\n, Spain, \n]  ...            NaN                     NaN   
4  [\n, Spain, \n]  ...            NaN                     NaN   

  CO₂-emissions (WLTP) Available from Taxi or rental car Availability  \
0                  NaN            NaN                NaN          NaN   
1                  NaN            NaN                NaN          NaN   
2                  NaN            NaN                NaN          NaN   
3                  NaN            NaN                NaN          NaN   
4                  NaN            NaN                NaN          NaN   

  Last timing belt change Electric Range (WLTP) Power consumption (WLTP)  \
0                     NaN                   NaN                      NaN   
1                     NaN                   NaN                      NaN   
2                     NaN                   NaN                      NaN   
3                     NaN                   NaN                      NaN   
4                     NaN                   NaN                      NaN   

  Battery Ownership  
0               NaN  
1               NaN  
2               NaN  
3               NaN  
4               NaN  

[5 rows x 58 columns]

In [5]:
df.shape

(29480, 58)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29480 entries, 0 to 29479
Data columns (total 58 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   make_model                28630 non-null  object 
 1   short_description         28630 non-null  object 
 2   make                      28630 non-null  object 
 3   model                     28630 non-null  object 
 4   location                  28630 non-null  object 
 5   price                     28630 non-null  object 
 6   Body type                 28630 non-null  object 
 7   Type                      28630 non-null  object 
 8   Doors                     28271 non-null  object 
 9   Country version           16889 non-null  object 
 10  Offer number              23100 non-null  object 
 11  Warranty                  15784 non-null  object 
 12  Mileage                   28629 non-null  object 
 13  First registration        28628 non-null  object 
 14  Gearbo

In [7]:
df.head().T

0  \
make_model                                               Mercedes-Benz A 160   
short_description                                                        CDi   
make                                                       \nMercedes-Benz\n   
model                                                        [\n, A 160 ,\n]   
location                   P.I. EL PALMAR C/FORJA 6,  11500 PUERTO DE SAN...   
price                                                             € 16,950.-   
Body type                                                  [\n, Compact, \n]   
Type                                                          [\n, Used, \n]   
Doors                                                            [\n, 5, \n]   
Country version                                              [\n, Spain, \n]   
Offer number                                               [\n, 7468157, \n]   
Warranty                                                 [\n, 24 months, \n]   
Mileage                                                           120,200 km   
First registration                                                   06/2016   
Gearbox                                                         [\nManual\n]   
Fuel type                                                             Diesel   
Colour                                                                 Black   
Paint                                                               Metallic   
desc                       [ , Precio al contado: 16950 euros,  ,  , Vehí...   
seller                                                                Dealer   
Seats                                                                    NaN   
Power                                                                    NaN   
Engine size                                                              NaN   
Gears                                                                    NaN   
CO₂-emissions                                                            NaN   
Manufacturer colour                                                      NaN   
Drivetrain                                                               NaN   
Cylinders                                                                NaN   
Fuel consumption                                                         NaN   
\nComfort & Convenience\n                                                NaN   
\nEntertainment & Media\n                                                NaN   
\nSafety & Security\n                                                    NaN   
\nExtras\n                                                               NaN   
Empty weight                                                             NaN   
Model code                                                               NaN   
General inspection                                                       NaN   
Last service                                                             NaN   
Full service history                                                     NaN   
Non-smoker vehicle                                                       NaN   
Emission class                                                           NaN   
Emissions sticker                                                        NaN   
Upholstery colour                                                        NaN   
Upholstery                                                               NaN   
Production date                                                          NaN   
Previous owner                                                           NaN   
Other fuel types                                                         NaN   
Power consumption                                                        NaN   
Energy efficiency class                                                  NaN   
CO₂-efficiency                                                           NaN   
Fuel consumption (WLTP)                                                  Na

In [8]:
df.sample(100).T

27044  \
make_model                                                         Volvo C70   
short_description          Convertible 2.4 Kinetic Leer, Stoelv, Clima, L...   
make                                                               \nVolvo\n   
model                                                          [\n, C70 ,\n]   
location                                 Neereind 1,  3998 WJ SCHALKWIJK, NL   
price                                                             € 11,950.-   
Body type                                              [\n, Convertible, \n]   
Type                                                          [\n, Used, \n]   
Doors                                                            [\n, 2, \n]   
Country version                                                          NaN   
Offer number                                              [\n, JD-565-F, \n]   
Warranty                                                                 NaN   
Mileage                                                           143,447 km   
First registration                                                   11/2006   
Gearbox                                                         [\nManual\n]   
Fuel type                                                           Gasoline   
Colour                                                                  Blue   
Paint                                                                    NaN   
desc                       [Volvo C70 Convertible 2.4 Kinetic Leer, Stoel...   
seller                                                                Dealer   
Seats                                                            [\n, 4, \n]   
Power                                                  [\n103 kW (140 hp)\n]   
Engine size                                                   [\n2,435 cc\n]   
Gears                                                                    NaN   
CO₂-emissions                                               212 g/km (comb.)   
Manufacturer colour                                                Niebieski   
Drivetrain                                                   [\n, Front, \n]   
Cylinders                                                            [\n5\n]   
Fuel consumption           [[8.9 l/100 km (comb.)], [12.8 l/100 km (city)...   
\nComfort & Convenience\n  [Air conditioning, Automatic climate control, ...   
\nEntertainment & Media\n              [CD player, On-board computer, Radio]   
\nSafety & Security\n      [ABS, Alarm system, Bi-Xenon headlights, Centr...   
\nExtras\n                 [Alloy wheels (17"), Automatically dimming int...   
Empty weight                                                  [\n1,598 kg\n]   
Model code                                                               NaN   
General inspection                                                   05/2023   
Last service                                                             NaN   
Full service history                                                     Yes   
Non-smoker vehicle                                                       NaN   
Emission class                                                        Euro 4   
Emissions sticker                                                        NaN   
Upholstery colour                                                        NaN   
Upholstery                                                      Full leather   
Production date                                                          NaN   
Previous owner                                    [[143,447 km, 11/2006], 2]   
Other fuel types                                                         NaN   
Power consumption                                                        NaN   
Energy efficiency class                                                  NaN   
CO₂-efficiency                                                           NaN   
Fuel consumption (WLTP)                                                

In [9]:
df.describe()

Production date
count          5908.00
mean           2018.00
std               6.49
min            1954.00
25%            2018.00
50%            2019.00
75%            2021.00
max            2022.00

### Öncelikle column isimlerini standardize edelim.

In [10]:
# column isimlerini ara bosluklari (_), ve sag-soldaki terimlerim trim yapalim.

df.columns


Index(['make_model', 'short_description', 'make', 'model', 'location', 'price',
       'Body type', 'Type', 'Doors', 'Country version', 'Offer number',
       'Warranty', 'Mileage', 'First registration', 'Gearbox', 'Fuel type',
       'Colour', 'Paint', 'desc', 'seller', 'Seats', 'Power', 'Engine size',
       'Gears', 'CO₂-emissions', 'Manufacturer colour', 'Drivetrain',
       'Cylinders', 'Fuel consumption', '\nComfort & Convenience\n',
       '\nEntertainment & Media\n', '\nSafety & Security\n', '\nExtras\n',
       'Empty weight', 'Model code', 'General inspection', 'Last service',
       'Full service history', 'Non-smoker vehicle', 'Emission class',
       'Emissions sticker', 'Upholstery colour', 'Upholstery',
       'Production date', 'Previous owner', 'Other fuel types',
       'Power consumption', 'Energy efficiency class', 'CO₂-efficiency',
       'Fuel consumption (WLTP)', 'CO₂-emissions (WLTP)', 'Available from',
       'Taxi or rental car', 'Availability', 'Last timing b

In [11]:
for i in df.columns:
    df.rename(columns={i:i.lower().replace(' & ','_').replace(' ','_').replace('\n','').replace('-','_')},inplace = True)


In [12]:
df.columns

Index(['make_model', 'short_description', 'make', 'model', 'location', 'price',
       'body_type', 'type', 'doors', 'country_version', 'offer_number',
       'warranty', 'mileage', 'first_registration', 'gearbox', 'fuel_type',
       'colour', 'paint', 'desc', 'seller', 'seats', 'power', 'engine_size',
       'gears', 'co₂_emissions', 'manufacturer_colour', 'drivetrain',
       'cylinders', 'fuel_consumption', 'comfort_convenience',
       'entertainment_media', 'safety_security', 'extras', 'empty_weight',
       'model_code', 'general_inspection', 'last_service',
       'full_service_history', 'non_smoker_vehicle', 'emission_class',
       'emissions_sticker', 'upholstery_colour', 'upholstery',
       'production_date', 'previous_owner', 'other_fuel_types',
       'power_consumption', 'energy_efficiency_class', 'co₂_efficiency',
       'fuel_consumption_(wltp)', 'co₂_emissions_(wltp)', 'available_from',
       'taxi_or_rental_car', 'availability', 'last_timing_belt_change',
       'e

In [13]:
df.isnull().sum()

make_model                    850
short_description             850
make                          850
model                         850
location                      850
price                         850
body_type                     850
type                          850
doors                        1209
country_version             12591
offer_number                 6380
warranty                    13696
mileage                       851
first_registration            852
gearbox                      1098
fuel_type                    2637
colour                       2574
paint                       14985
desc                         1433
seller                        850
seats                        3975
power                        1422
engine_size                  2253
gears                       10526
co₂_emissions               10886
manufacturer_colour          7693
drivetrain                  12587
cylinders                   10628
fuel_consumption             6095
comfort_conven

In [14]:
df.isnull().sum()/df.shape[0]*100

make_model                  2.88
short_description           2.88
make                        2.88
model                       2.88
location                    2.88
price                       2.88
body_type                   2.88
type                        2.88
doors                       4.10
country_version            42.71
offer_number               21.64
warranty                   46.46
mileage                     2.89
first_registration          2.89
gearbox                     3.72
fuel_type                   8.95
colour                      8.73
paint                      50.83
desc                        4.86
seller                      2.88
seats                      13.48
power                       4.82
engine_size                 7.64
gears                      35.71
co₂_emissions              36.93
manufacturer_colour        26.10
drivetrain                 42.70
cylinders                  36.05
fuel_consumption           20.68
comfort_convenience        13.73
entertainm

In [60]:
df['battery_ownership'].unique()

array([nan, 'Included'], dtype=object)

In [61]:
df['battery_ownership'].value_counts()

Included    7
Name: battery_ownership, dtype: int64

### 'emission_class' column una data cleaning uygulayalim nan degerler disinda numerik veriler haline getirelim. Emission sinifini 'Euro' ve diger ifadelerden kurtaralim.

In [15]:
df['emission_class'].unique()

array([nan, 'Euro 4', 'Euro 6', 'Euro 6d-TEMP', 'Euro 5', 'Euro 6d',
       'Euro 6c', 'Euro 3', 'Euro 2', 'Euro 1'], dtype=object)

In [16]:
df['emission_class'] = df.emission_class.str.strip("dTEMP-c")

In [17]:
df['emission_class'].unique() #dtype:float missig value lari doldurduktan sonra int yapabiliriz.

array([nan,  4.,  6.,  5.,  3.,  2.,  1.])

### emissions_sticker

In [18]:
df['emissions_sticker'].unique()

array([nan, '4 (Green)', '1 (No sticker)', '3 (Yellow)', '2 (Red)'],
      dtype=object)

In [19]:
df['emissions_sticker'] = df['emissions_sticker'].str.strip(" )(1432")
df['emissions_sticker'].unique()

array([nan,  4.,  1.,  3.,  2.])

### upholstery_colour
#### white, black, other

In [20]:
df['upholstery_colour'].unique()

array([nan, 'Black', 'Grey', 'Other', 'Blue', 'Brown', 'Beige', 'Red',
       'White', 'Orange', 'Yellow', 'Green'], dtype=object)

In [21]:
colour = ['Black', 'Grey', 'Other', 'Blue', 'Brown', 'Beige', 'Red', 'White', 'Orange', 'Yellow', 'Green']
for i in colour:
    if i=='White':
        df['upholstery_colour'] = df['upholstery_colour'].str.replace(i,'white')
    elif i=='Black':
        df['upholstery_colour'] = df['upholstery_colour'].str.replace(i,'black')
    else :
        df['upholstery_colour'] = df['upholstery_colour'].str.replace(i,'other')


In [22]:
df['upholstery_colour'].unique()

array([nan, 'black', 'other', 'white'], dtype=object)

### upholstery
#### leather, other

In [23]:
df['upholstery'].unique()

array([nan, 'Cloth', 'Full leather', 'Part leather', 'Other', 'alcantara',
       'Velour'], dtype=object)

In [24]:
origin = ['Cloth', 'Full leather', 'Part leather', 'Other', 'alcantara',
       'Velour']
for i in origin:
    if i=='Full leather' or i=='Part leather':
        df['upholstery'] = df['upholstery'].str.replace(i,'leather')
    else :
        df['upholstery'] = df['upholstery'].str.replace(i,'other')

In [25]:
df['upholstery'].unique()

array([nan, 'other', 'leather'], dtype=object)

### production_date

In [26]:
df['production_date'].unique()

array([  nan, 2019., 2021., 2018., 2014., 2011., 2020., 2022., 2017.,
       2016., 2013., 2008., 2002., 1991., 2010., 2006., 2012., 1999.,
       2015., 1997., 2004., 1996., 1962., 2005., 2003., 2007., 1993.,
       1994., 2009., 2001., 1985., 1970., 1990., 1998., 1981., 1995.,
       1973., 2000., 1978., 1987., 1982., 1988., 1966., 1965., 1967.,
       1961., 1968., 1954., 1969., 1976.])

In [59]:
df['production_date'].value_counts()

2019.00    1179
2021.00     980
2022.00     894
2020.00     763
2018.00     762
2017.00     391
2016.00     239
2015.00     118
2014.00      90
2013.00      76
2010.00      53
2012.00      43
2011.00      43
2008.00      34
2009.00      26
2007.00      20
2006.00      17
2002.00      15
2004.00      13
2003.00      13
1967.00      12
2001.00      12
1966.00      11
1999.00       9
2005.00       9
1965.00       9
1970.00       9
1997.00       8
1994.00       8
1968.00       7
2000.00       7
1998.00       5
1990.00       3
1973.00       3
1987.00       3
1993.00       3
1991.00       3
1996.00       3
1995.00       2
1969.00       2
1978.00       2
1982.00       2
1961.00       1
1954.00       1
1988.00       1
1962.00       1
1981.00       1
1985.00       1
1976.00       1
Name: production_date, dtype: int64

### previous_owner

In [27]:
df['previous_owner'].sample(100)

21808                           NaN
21426      [[6,609 km, 05/2021], 1]
18987                           NaN
10379                           NaN
23435                           NaN
                    ...            
7014                            NaN
6577     [[238,853 km, 06/2012], 2]
13337      [[2,500 km, 07/2022], 1]
28828    [[117,042 km, 11/2013], 2]
26055                           NaN
Name: previous_owner, Length: 100, dtype: object

In [28]:
df['previous_owner'] = df['previous_owner'].str[-1].astype(float)
df['previous_owner'].unique()

array([nan,  2.,  1.,  3.,  6.,  4.,  8.,  5.,  7.,  9., 10., 14., 13.,
       12.])

In [29]:
df['previous_owner'].sample(20)

26433    NaN
18834   1.00
403     1.00
11533    NaN
9043     NaN
22196   1.00
7286     NaN
28982   1.00
8704     NaN
3839     NaN
20762    NaN
16671    NaN
15296   2.00
3824    2.00
21519   3.00
3491     NaN
25194    NaN
13891    NaN
3251     NaN
22911    NaN
Name: previous_owner, dtype: float64

### other_fuel_types
#### hydogen, other

In [30]:
df['other_fuel_types'].unique()

array([nan, 'Electricity', 'Hydogen', 'Super E10 95'], dtype=object)

In [31]:
f_type = ['Electricity', 'Hydogen', 'Super E10 95']
for i in f_type:
    if i=='Hydogen':
        df['other_fuel_types'] = df['other_fuel_types'].str.replace(i,'hydogen')
    else :
        df['other_fuel_types'] = df['other_fuel_types'].str.replace(i,'other')

In [32]:
df['other_fuel_types'].unique()

array([nan, 'other', 'hydogen'], dtype=object)

### energy_efficiency_class
#### energy_efficiency_class : A, other

In [33]:
df['energy_efficiency_class'].unique()

array([nan, 'C', 'B', 'E', 'D', 'A', 'G', 'F', 'A+', 'A+++', 'A++'],
      dtype=object)

In [34]:
df['energy_efficiency_class'] = df['energy_efficiency_class'].str.strip('+')

e_class = ['C', 'B', 'E', 'D', 'G', 'F']
for i in e_class:
   df['energy_efficiency_class'] = df['energy_efficiency_class'].str.replace(i,'other')

In [35]:
df['energy_efficiency_class'].unique()

array([nan, 'other', 'A'], dtype=object)

### co₂_efficiency

In [36]:
df['co₂_efficiency'].unique() #drop?

array([nan,
       'Calculated on basis of measured CO₂-emissions taking into account the mass of the vehicle.'],
      dtype=object)

In [37]:
df['co₂_efficiency'].sample(40) #drop edilmesi düsünülebilinir.

19050    Calculated on basis of measured CO₂-emissions ...
25484                                                  NaN
25731                                                  NaN
12678    Calculated on basis of measured CO₂-emissions ...
3548                                                   NaN
7749                                                   NaN
13272    Calculated on basis of measured CO₂-emissions ...
11042                                                  NaN
17670                                                  NaN
27138                                                  NaN
6831                                                   NaN
5781     Calculated on basis of measured CO₂-emissions ...
20480                                                  NaN
21329                                                  NaN
28302    Calculated on basis of measured CO₂-emissions ...
25378                                                  NaN
6092     Calculated on basis of measured CO₂-emissions .

In [38]:
df.sample(100).T

18276  \
make_model                                               Toyota Yaris Cross   
short_description                                          120H Active Tech   
make                                                             \nToyota\n   
model                                                 [\n, Yaris Cross ,\n]   
location                                  AVDA. PORTUGAL 8,  24009 LEÓN, ES   
price                                                            € 23,280.-   
body_type                                        [\n, Off-Road/Pick-up, \n]   
type                                               [\n, Pre-registered, \n]   
doors                                                           [\n, 5, \n]   
country_version                                             [\n, Spain, \n]   
offer_number                                              [\n, 7296076, \n]   
warranty                                                [\n, 60 months, \n]   
mileage                                                                3 km   
first_registration                                                  08/2022   
gearbox                                                     [\nAutomatic\n]   
fuel_type                                                               NaN   
colour                                                                 Grey   
paint                                                                   NaN   
desc                      [ , Precio al contado: 25945 euros,  , Toyota ...   
seller                                                               Dealer   
seats                                                           [\n, 5, \n]   
power                                                  [\n85 kW (116 hp)\n]   
engine_size                                                  [\n1,490 cc\n]   
gears                                                               [\n1\n]   
co₂_emissions                                                           NaN   
manufacturer_colour                                            BRONCE OLIVA   
drivetrain                                                  [\n, Front, \n]   
cylinders                                                           [\n4\n]   
fuel_consumption                                     [[0 l/100 km (comb.)]]   
comfort_convenience                                                     NaN   
entertainment_media                                                     NaN   
safety_security                                                         NaN   
extras                                                                  NaN   
empty_weight                                                 [\n1,485 kg\n]   
model_code                                                              NaN   
general_inspection                                                      NaN   
last_service                                                            NaN   
full_service_history                                                    NaN   
non_smoker_vehicle                                                      NaN   
emission_class                                                          NaN   
emissions_sticker                                                       NaN   
upholstery_colour                                                       NaN   
upholstery                                                              NaN   
production_date                                                         NaN   
previous_owner                                                          NaN   
other_fuel_types                                                      other   
power_consumption                                                       NaN   
energy_efficiency_class                                                 NaN   
co₂_efficiency                                                          NaN   
fuel_consumption_(wltp)                                                 NaN   
co₂_emissions_(wltp)                     

In [71]:
df["comfort_convenience"] = [",".join(item) if type(item) == list else item for item in df["comfort_convenience"]]

In [74]:
df["comfort_convenience"].value_counts(dropna=False)

NaN                                                                                                                                                                                                                                                                                                                                                                                                            4047
Air conditioning, Automatic climate control, Electrical side mirrors, Multi-function steering wheel, Power windows                                                                                                                                                                                                                                                                                              244
Air conditioning, Automatic climate control, Cruise control                                                                                                                                     

In [82]:
A= ['Parking assist system sensors rear', 'Rain sensor', 'Seat heating', 'Split rear seats', 'Start-stop system', 'Tinted windows']
C= ['Air conditioning','Electrical side mirrors']

for i in A:
    if df['comfort_convenience'].str.contains(i) and df['comfort_convenience'].str.contains('Seat heating') and df['comfort_convenience'].str.contains('Rain sensor') and df['comfort_convenience'].str.contains('Split rear seats') and df['comfort_convenience'].str.contains('Start-stop system') and df['comfort_convenience'].str.contains('Tinted windows'):
    df['comfort_convenience']='A'
elif df['comfort_convenience'].str.contains('Air conditioning') and df['comfort_convenience'].str.contains('Electrical side mirrors'):
     df['comfort_convenience']='C'  
else:
    df['comfort_convenience']='B' 



ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

### 'make'

In [39]:
df['make'].unique()

array(['\nMercedes-Benz\n', nan, '\nOpel\n', '\nRenault\n', '\nPeugeot\n',
       '\nFiat\n', '\nSEAT\n', '\nSkoda\n', '\nDacia\n', '\nToyota\n',
       '\nNissan\n', '\nFord\n', '\nHyundai\n', '\nVolvo\n'], dtype=object)

In [40]:
df['make'] = df['make'].str.strip('\n')

In [41]:
df['make'].unique()

array(['Mercedes-Benz', nan, 'Opel', 'Renault', 'Peugeot', 'Fiat', 'SEAT',
       'Skoda', 'Dacia', 'Toyota', 'Nissan', 'Ford', 'Hyundai', 'Volvo'],
      dtype=object)

### 'model'

In [42]:
df['model'] = df['model'].str.join(",").str.strip('\n,')

In [43]:
df['model'].unique() #nasil yapilacagi tartisilabilinir..

array([' A 160 ', ' EQE 350 ', ' A 45 AMG ', ' A 35 AMG ', ' C 160 ',
       ' CLA 180 ', ' A 220 ', ' A 200 ', ' A 250 ', ' A 180 ',
       ' GLC 220 ', ' E 220 ', ' B 200 ', ' A 150 ', ' V 220 ',
       ' AMG GT ', ' E 300 ', ' EQS ', ' A 140 ', '  ', ' CL ', ' B 180 ',
       ' GLB 200 ', ' E 350 ', ' CLA 200 ', ' 280 ', ' GLA 180 ',
       ' Viano ', ' E 53 AMG ', ' SLK 200 ', ' GLE 350 ', ' 220 ',
       ' SL 500 ', ' E 400 ', ' SLC 43 AMG ', ' SL 350 ', ' SLC 250 ',
       ' SLK 350 ', ' SLS ', ' CLK 200 ', ' C 400 ', ' SL 65 AMG ',
       ' C 43 AMG ', ' C 63 AMG ', ' SLK 250 ', ' 500 ', ' SLK 300 ',
       ' SLC 200 ', ' SLK 55 AMG ', ' S 63 AMG ', ' 230 ', ' E 500 ',
       ' SLK ', ' SL 55 AMG ', ' CLK 55 AMG ', ' C 300 ', ' SLK 280 ',
       ' E 450 ', ' SLC 180 ', ' C 200 ', ' E 200 ', ' SL 63 AMG ',
       ' SL 300 ', ' S 560 ', ' C 180 ', ' C 250 ', ' C 220 ', ' E 250 ',
       ' SL 560 ', ' SLK 230 ', ' SL 280 ', ' SL 380 ', ' SL 600 ',
       ' G 500 ', ' 190 ', ' 250 '

### 'location'

In [44]:
df['location'].unique()

array(['P.I. EL PALMAR C/FORJA 6,  11500 PUERTO DE SANTA MARIA, ES',
       'APARTADO DE CORREOS 1032,  26140 LOGROÑO, ES',
       'PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8,  43004 TARRAGONA, ES',
       ..., '2521AA DEN HAAG, NL', '1000 Brussel, BE',
       'Sur rendez-vous,  5060 Sambreville, BE'], dtype=object)

In [45]:
df['location'] = df['location'].str[-2:]

In [46]:
df['location'].unique()

array(['ES', 'DE', 'BE', 'AT', 'NL', 'FR', 'IT', nan, 'LU', 'DK', 'EE',
       'BG'], dtype=object)

### 'price'

In [47]:
df['price'].unique()

array(['€ 16,950.-', '€ 80,900.-', '€ 69,900.-', ..., '€ 43,420.-',
       '€ 36,795.-', '€ 4,440.-'], dtype=object)

In [48]:
df['price'] = df['price'].str.strip('€.- ').str.replace(",", "").astype(float)

In [49]:
df['price'].unique()

array([16950., 80900., 69900., ..., 43420., 36795.,  4440.])

### 'body_type'

In [50]:
df['body_type'] = df['body_type'].str.join(",").str.strip(',\n ')

In [51]:
df['body_type'].unique() #daha calisilabilinir mi

array(['Compact', 'Convertible', 'Coupe', 'Off-Road/Pick-up',
       'Station wagon', nan, 'Sedan'], dtype=object)

### 'type'

In [53]:
df['type'].sample(5)

3747     [\n, Pre-registered, \n]
11091              [\n, Used, \n]
20375              [\n, Used, \n]
13079              [\n, Used, \n]
2290               [\n, Used, \n]
Name: type, dtype: object

In [54]:
df['type'] = df['type'].str.join(",").str.strip(',\n ')

In [55]:
df['type'].unique() #daha calisilabilinir mi

array(['Used', 'Pre-registered', 'Demonstration', "Employee's car", nan],
      dtype=object)

### 'doors'

In [56]:
df['doors'].sample(5)

21723    [\n, 5, \n]
28175    [\n, 5, \n]
25301    [\n, 5, \n]
4830     [\n, 5, \n]
20297    [\n, 5, \n]
Name: doors, dtype: object

In [57]:
df['doors'] = df['doors'].str.join(",").str.strip(',\n ').astype(float)

In [58]:
df['doors'].unique()

array([ 5.,  4.,  3.,  2., nan,  1.,  6.])

# PART- 2 `( Handling With Missing Vales )`

# PART- 3 `( Handling With Outliers )`

# Final Step (Checking final situation of data via graphs)

## Export dataframe to csv file (without dummy)

In [ ]:
df.to_csv("final_scout_not_dummy.csv", index=False)

# Dummy Operation

## Export dataframe to csv file (dummy)

In [ ]:
df_dummied.to_csv("final_scout_dummy.csv", index=False)